language:
          python

python:
  - "3.6.5"

install:
  - pip install -r requirements.txt
  - pip install coveralls
   - pip install pytest-cov

 
script:
  - pytest --cov=YourModule/
  
after_success:
  - coveralls
